///////////////////////////////////////////////////////////
//  DispersorPagoException.cs
//  Implementation of the Class DispersorPagoException
//  Generated by Enterprise Architect
//  Created on:      25-oct-2017 11:30:57 a.m.
//  Original author: Desarollo_Transforma
///////////////////////////////////////////////////////////
//using Estructural.Clases.Conciliacion.Migracion.Runtime.Validacion;
using Estructural.Clases.Conciliacion.RunTime.ReglasDeNegocio;
using ValidacionArchivosConciliacion;

public class DispersorPagoException {

	private DetalleValidacion resultadovalidacion;

	public DispersorPagoException(){

	}

	~DispersorPagoException(){

	}

	public virtual void Dispose(){

	}

	public DetalleValidacion ResultadoValidacion{
		get{ return resultadovalidacion; }
        set{ resultadovalidacion = value; }
    }

}//end DispersorPagoException